etcJupyter:
  # Options for Jupyter Notebook itself, set for each user
  jupyter_notebook_config.json: {}

nfsPVC:
  enabled: false
  # If you want a PVC with NFS that can be used to mount home directories
  #nfs:
    #serverIP: fs-d59c0f7f.efs.us-west-2.amazonaws.com # IP of your NFS Server
    #shareName: hackweek-cluster-home-dirs # Path of your NFS share export

jupyterhub: 
  #proxy:
    #secretToken: "in-another-file-that-is-encrypted"
    #https:
      #enabled: false
      #hosts:
      #  - icesat-2.hackweek.io
      #letsencrypt:
      #  contactEmail: scottyh@uw.edu

  prePuller:
    continuous:
      enabled: false
    hook:
      enabled: false

  scheduling:
    userScheduler:
      enabled: false
    userPods:
      nodeAffinity:
        matchNodePurpose: require

  singleuser:
    cloudMetadata: # taken care of by eksctl node configuration
      enabled: true
    defaultUrl: "/lab"
    #serviceAccountName: jovyan
    #initContainers:
    #  - name: volume-mount-hack
    #    image: busybox
    #    command:
    #      - "sh"
    #      - "-c"
    #      - >
    #        id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan ;
    #      #  id && chown 1000:1000 /srv/shared && ls -lhd /srv/shared ;
    #    securityContext:
    #      runAsUser: 0
    #    volumeMounts:
    #      - name: home
    #        mountPath: /home/jovyan
    #        subPath: "home/{username}"
          #- name: jupyterhub-shared
          #  mountPath: /srv/shared
          #  subPath: "hackweek.pangeo.io/shared"
    #extraVolumes:
    #  - name: jupyterhub-shared
    #    persistentVolumeClaim:
    #      claimName: data-nfs
      #static:
      #  pvcName: home-nfs
      #  subPath: "home/{username}"
      #requires having run config/shared--nfs.yaml
      #extraVolumeMounts:
      #  - name: jupyterhub-shared
      #    mountPath: /srv/shared
      #    subPath: "icesat2.pangeo.io/shared"
      #extraVolumes:
      #  - name: jupyterhub-shared
      #    persistentVolumeClaim:
      #      claimName: shared-nfs
    # Only settings required to use the efs-provisioner
    storage:
      dynamic:
        storageClass: aws-efs
    startTimeout: 600
    cpu:
      limit: 4
      guarantee: 3
    memory:
      limit: 16G
      guarantee: 14G

    profileList:
      - display_name: "base-image-dev"
        kubespawner_override:
          image: pangeodev/base-image:latest
      - display_name: "pangeo-image-dev"
        kubespawner_override:
          image: pangeodev/pangeo-image:latest
      - display_name: "ml-image-dev"
        kubespawner_override: 
          image: pangeodev/ml-image:latest

  hub:
    resources: # should fill up single node to near capacity
      requests:
        cpu: 1
        memory: 0.75G
      limits:
        cpu: 1
        memory: 1G
    extraConfig:
      jupyterlab: |
        c.Spawner.cmd = ['jupyter-labhub']

    # z2jh customizations go here

