jupyterhub:
  #prePuller:
    #continuous:
      # Don't need continuous pre-puller on staging
      #enabled: false
  proxy:
    https:
      #enabled: false
      hosts:
        - staging.icesat-2.hackweek.io
      letsencrypt:
        contactEmail: scottyh@uw.edu
  singleuser:
    profileList:
      - display_name: "IceSat-2 Hackweek 2020 Image"
        default: true
        kubespawner_override:
          image: uwhackweeks/icesat2:master
  auth:
    github:
      callbackUrl: "http://staging.icesat-2.hackweek.io/hub/oauth_callback"
  hub:
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 0.5
        memory: 1G
