name: Build Images
on:
  pull_request:
    branches-ignore:
      # We run don't want a PR build for staging -> master PRs
      - prod


jobs:
  build:
    name:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://sebialvis/hubploy:2020021923263068ef3a
        name: test building image
        with:
          args: build hackweek-hub